sudo: false
addons:
  apt:
    packages:
    - git
language: java
jdk: oraclejdk8
branches:
  except:
  - /^v\d+\.\d+\.\d+$/
before_install:
- git fetch
- git config user.email "paul.schiffgens@maibornwolff.de"
- git config user.name "paulschiffgens"
- git config url.https://.insteadOf git://
- git checkout -qf $TRAVIS_BRANCH
install:
- echo "skip default gradlew assemble"
script:
- ./gradlew release --info --stacktrace