sudo: false
addons:
  apt:
    packages:
    - git
language: java
jdk: oraclejdk7
env: TERM=dumb
branches:
  except:
  - /^v\d+\.\d+\.\d+$/
before_install:
- git fetch
- git config user.email "paul.schiffgens@maibornwolff.de"
- git config user.name "paulschiffgens"
- git config url.https://.insteadOf git://
- git checkout -qf $TRAVIS_BRANCH
install:
- echo "skip default gradlew assemble"
script:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && ./gradlew release -Dorg.ajoberstar.grgit.auth.username=${GH_TOKEN} -Dorg.ajoberstar.grgit.auth.password --info --stacktrace || ./gradlew build --info --stacktrace'