/*
 * This Java source file was generated by the Gradle 'init' task.
 */
class Library {
    boolean someLibraryMethod() {
        return true;
    }

    void helloWorld() {
        System.out.println("HelloWorld");
    }

    void helloWorld2() {
        System.out.println("HelloWorld2");
    }
}
