/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    void helloWorld4() {
        System.out.println("Hello World 4");
    }

    void helloWorld5() {
        System.out.println("Hello World 5");
    }

    void helloWorld6() {
        System.out.println("Hello World 6");
    }
}
